#include<stdio.h>
void main(){

    int x = 10;
    int i = 1;

    fordemo:
        printf("I love Coding....\n");

        for (;i <= x;)
        {
            i++;
            goto fordemo;
        }
        printf("After for loop\n");
}
/*
I love Coding....
I love Coding....
I love Coding....
I love Coding....
I love Coding....
I love Coding....
I love Coding....
I love Coding....
I love Coding....
I love Coding....
I love Coding....
After for loop*/